### ISSUE TITLE
Repeat Button in Miniplayer

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#10]
**Your osu!player username**
Login

**Describe the bug**
Repeat Song button doen't work in Miniplayer

**Expected behavior**
It should repeat the song.

**Additional context**
Running version v74

**Comment by Founntain** [comment]
Works as intended: (Click is hard to see tho, but repeats the song) https://x.founntain.de/xObR5XXI.mp4

**Comment by Founntain** [comment]
Merged with #11
