### ISSUE TITLE
Repeat not working when "Skip song with same name" is enabled

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#11]
**Your osu!player username**
Login

**Describe the bug**
Title

**Expected behavior**
It should Repeat the song with the button turned on, but it doesn't.

**Additional context**
Running v74

**Comment by Founntain** [comment]
Works as intended: https://x.founntain.de/TZCt31eD.mp4

**Comment by Installieren** [comment]
Wearend ich "Ueberspringe namen mit selben song" an habe geht der Repeat button nicht mehr.

**Comment by Founntain** [comment]
Fixed in new version
