### ISSUE TITLE
[BUG] Custom Background Image setting not working

### ISSUE THREAD

**Issue by lordalric123** [Founntain/osuplayer-issues#12]
ID: Z1reth

**Describe the bug**
When I customize theme and then check the option "Use Custom background image" and select a  picture it says "Theme Saved, Please restart to see the changes" but when i restart there was no change

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Customize theme'
3. check the option "Use Custom background image"
4. Click "Select Custom Background"
5. Click "Save Theme"
6. Restart App
7. See error

**Expected behavior**
A clear and concise description of what you expected to happen: 
Expected to see my selected custom background

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Additional context**
Add any other context about the problem here:

**Comment by Founntain** [comment]
Fixed in Version 76
