### ISSUE TITLE
[FEATURE] Change the ??? of the converted songs to alphabets so that its easy to find the song

### ISSUE THREAD

**Issue by lordalric123** [Founntain/osuplayer-issues#13]
**What do you would like to see in the player?**
Change the ??? on the converted songs to the first letter of the converted songs, so that i can easily find said song

**How would you like to see the feature? E.g. the way implemented or displayed**
the displayed example should be like this:
Original: ??? - Linked Horizon - Sasageyo
Changed: L - Linked Horizon - Sasageyo

**Additional context**
Add any additional context here

**Comment by Founntain** [comment]
Implemented in next version
