### ISSUE TITLE
[BUG] Background Dim Reset When Re-Open Setting Menu

### ISSUE THREAD

**Issue by nattadasu** [Founntain/osuplayer-issues#14]
**Your osu!player username**
nattadasu

**Describe the bug**
As the title of this issue, player setting of background dim would be reset to 100% opacity when user re-open settings menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Settings.
2. Config "Background Dim" to `< 100%` of opacity, configuration supposed to be saved automatically.
3. Go to any menu except Settings. In this scenario, Home menu was chosen.
4. Go back to Settings menu, config suddenly reset to 100%.

**Expected behaviour**
Dim config was saved automatically, and not getting reset.

**Additional context**
v79, using English and Indonesian. Application restarted when bug was noticed. Parallax and blur config weren't affected by this bug. No `.json` editing "involved."

**Comment by Founntain** [comment]
Issue was reproduceable

**Comment by Founntain** [comment]
Fixed in version 81
