### ISSUE TITLE
[BUG] Hotkeys still work even when player window inactive

### ISSUE THREAD

**Issue by enyoukai** [Founntain/osuplayer-issues#15]
**Describe the bug**
Even when you have the player window minimized, pressing any hotkey will be registered by the player. The hotkey will also not work on the active window.

**To Reproduce**
1. Minimize the player
2. Use any hotkey

**Expected behavior**
The hotkey should work normally on the active window without the player registering them.

**Comment by Founntain** [comment]
The player registers the Hotkeys as global hotkeys this means it doesnt matter if the player is fullscreened, active, inactive or minimized. The hotkeys always work, they only get unregistered when you close / shutdown the player

**Comment by Founntain** [comment]
Closed due to inactivity
