### ISSUE TITLE
[FEATURE] "Apply Theme" Button

### ISSUE THREAD

**Issue by nattadasu** [Founntain/osuplayer-issues#16]
**What do you would like to see in the player?**
When theme set, add "Apply Theme" button to Theme setting for confirmation

**Additional context**
Due to discovered bugs on #17, it would be nice if we do have that button.

How button works is:
* When user selected a theme, apply button will be available.
* If button pressed, do cache flushing/deletion and set applied theme to as new cache.

**Comment by nattadasu** [comment]
Ups, I accidentally pressed submit button. Will edit on this issue

**Comment by Founntain** [comment]
What do you want to achieve with this? The need to confirm a theme change?

**Comment by nattadasu** [comment]
Yes, using a pop-up/dialogue box will be used as common behavioral due most of users will expect if program applied the setting (although if the application itself have auto save configurations).

**Comment by Founntain** [comment]
Well current behaviour is, that it saves the theme when clicking save theme. If you change the theme, the changes will be discarded and the selected theme will be loaded, sadly there is no way to check if there are active changes but can be looked into that.
