### ISSUE TITLE
[BUG] Dark/Light Icon Unable to Apply Using Theme Picker

### ISSUE THREAD

**Issue by nattadasu** [Founntain/osuplayer-issues#17]
**Your osu!player username**
nattadasu

**Describe the bug**
This bug will occur when an user selected a theme with different boolean value on `UseDarkIcons`, `UseDarkFont`, and/or `UseDarkControlIcons`, making user to manually flush theme data.

**To Reproduce**
1. Go to setting, and select Customize Theme
2. By preferences.
    * If user is currently selecting a theme:
      * Make sure the theme has different boolean value (`true` or `false`) on "Use dark font", "Use dark icons", and/or "Use dark control icons."
      * Do a restart
    * If user is downloading a new theme
      * Open "Browse Themes"
      * Download a theme with different boolean value (`true` or `false`) on "Use dark font", "Use dark icons", and/or "Use dark control icons." In this case, `The Vampire by nattadasu` is selected
      * Go back to Theme Editor, choose new theme.
      * Do a restart

**Expected behavior**
Icons and/or fonts with different boolean value will follow set properties.

**Screenshots**
![image](https://user-images.githubusercontent.com/49780229/113134579-2d96eb80-924b-11eb-8970-06c2f3dfc94d.png)

**Additional context**
I've tested on "If user is downloading a new theme" option one. If any possible suggestion for this, see #16.

**Comment by Founntain** [comment]
Fixed in new version

The checkboxes where never changed during load or theme change
