### ISSUE TITLE
[BUG] Hotkeys to Skip/Previous Track seem to repeat/skip multiple songs

### ISSUE THREAD

**Issue by Aethergarden** [Founntain/osuplayer-issues#18]
**Your osu!player username**
Magi

**Describe the bug**
When using ALT+LEFTARROW or ALT+RIGHTARROW, I've noticed that the player skips up to 4 tracks on one key combination. 

**To Reproduce**
1. Open the osu!player window
2. Begin music playback.
3. Use hotkeys to skip or go back tracks,
4. The player will skip/go back multiple tracks.

**Expected behavior**
The player skips **one** track, not multiple.

**Screenshots**
N/A

**Additional context**
Using Linear Optical keyswitches. Might just need to add a debounce to the keybinds.

**Comment by Founntain** [comment]
I got the issue reproduced, for me it always skips 2 songs.
Will look into it ASAP.

**Comment by Founntain** [comment]
Fixed
