### ISSUE TITLE
[BUG] Player randomly pauses after 10-11 tracks

### ISSUE THREAD

**Issue by Aethergarden** [Founntain/osuplayer-issues#19]
**Your osu!player username**
Magi

**Describe the bug**
When a new track begins playing, the player will play the track for a fraction of a second and pause shortly after.

**To Reproduce**
Open osu!player plus
Play 9-10 tracks
The 10th/11th track will randomly pause.

**Expected behavior**
The track should play normally without pauses.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Aethergarden** [comment]
Now seems to be happening after every track.

**Comment by Founntain** [comment]
Not reproducable at all. Listened to 20+ songs in a row without touching it. Played all songs.

**Comment by MrDubstep863** [comment]
It's actually with broken song in osu like "The Solace of Oblivion"

**Comment by Founntain** [comment]
> It's actually with broken song in osu like "The Solace of Oblivion"

Thats what I also noticed but your db shouldn't contain so many broken songs.

**Comment by Aethergarden** [comment]
Fixed by reinstalling all songs; seems to not be an issue with osu!player.
