### ISSUE TITLE
Adding a Fav Button in Miniplayer

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#2]
**What do you would like to see in the player?**
Favo Button in Miniplayer

**How would you like to see the feature? E.g. the way implemented or displayed**
While having the Miniplayer open, either bevor or after the song controls a small heart to add songs.

**Additional context**
Makes life nicer for all Miniplayer users.

**Comment by Founntain** [comment]
*Implemented and sheduled for v74*
