### ISSUE TITLE
[CRASH] cannot click Create playlists from collection.db

### ISSUE THREAD

**Issue by Noko916** [Founntain/osuplayer-issues#22]
**What did you do to trigger this crash?**
Crash when clicking the "Create playlists from collection.db" button

**Is there  a way to reproduce the crash?**
Clicking that button will cause problems

**If you a crashlog (logs folder) please attach it or include it below**
[20210616190059-[7484].txt](https://github.com/Founntain/osuplayer-issues/files/6662122/20210616190059-.7484.txt)

**Comment by Founntain** [comment]
Closed merged with #23 
Please don't open multiple crashreports for the same issue. Rather attach all crashlogs to one post.

Please add missing logs to #23
