### ISSUE TITLE
[FEATURE] Support for multiple songs in map packs

### ISSUE THREAD

**Issue by Noko916** [Founntain/osuplayer-issues#26]
**What do you would like to see in the player?**
I have a few music packs, but I don't know the song titles.
I need a way to know the song titles.

**How would you like to see the feature? E.g. the way implemented or displayed**
If same song title, put something like "[Difficulty Name]" after the song title to make it easier to understand.

**Additional context**
Example of a map with the same song title:
![screenshot3047](https://user-images.githubusercontent.com/57006237/122943481-06ffd100-d3b2-11eb-9e42-723ab6e632c5.jpg)
![image](https://user-images.githubusercontent.com/57006237/122943708-357dac00-d3b2-11eb-93bd-f0040168b955.png)

**Comment by Founntain** [comment]
Like this:
![](https://x.founntain.de/Nkl62USF.png)

Or like this:
![](https://x.founntain.de/4XE6BpuO.png)

**Comment by Founntain** [comment]
Will be in new version. I choosed the second idea.
