### ISSUE TITLE
[CRASH] Application crashes on RMB click

### ISSUE THREAD

**Issue by Flexlug** [Founntain/osuplayer-issues#28]
**What did you do to trigger this crash?**
Clicked right mouse button in secondary window.

**Is there  a way to reproduce the crash?**
1. Open secondary window;
2. Press right mouse button in any place of this window.

**If you a crashlog (logs folder) please attach it or include it below**
[20210903115128-[16064].txt](https://github.com/Founntain/osuplayer-issues/files/7104658/20210903115128-.16064.txt)
[20210903121819-[32684].txt](https://github.com/Founntain/osuplayer-issues/files/7104895/20210903121819-.32684.txt)

[video demo](https://user-images.githubusercontent.com/34001155/131982333-d793799b-b960-4e4b-a7ff-57ebfb8e9836.mp4)

**Comment by Founntain** [comment]
Reproducable, I though I already mae a fix for this. Thanks for bringing this up once more.
Fix will be in next version.

**Comment by Founntain** [comment]
Fixed in new version, when released.
