### ISSUE TITLE
Option to skip duplicate songs

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#4]
**What do you would like to see in the player?**
An option to skip songs with the same name.

**How would you like to see the feature? E.g. the way implemented or displayed**
An option that could be toggled within the main players option would be nice.

**Additional context**
No idea, if this is possible but, currently I have to skip more then once, since lets be honest, osu!pp mapping gave us to many versions of the same songs.

**Comment by Founntain** [comment]
So basicly a blacklist?

**Comment by Installieren** [comment]
"Blacklist" more or less means, removing it. I would rather call it Whitelist, so that songs with same names get skipped.

**Comment by Founntain** [comment]
Well it whitelist would be: All songs **not** on the whitelist will not be played.
A blacklist: Skips all songs, that are on the blacklist, but you would have need to fill it manually which is dumb.

So yeah a toggle for not playing duplicate songs should be possible.

**Comment by Installieren** [comment]
Okay, fuck the terms "Black- and Whitelist".
Lets just call it a fucking Song Name Filter, that checks, when turned on, if there are Song Names that are dubs.
If so, add them to a filter, that skips everything after playing it once.

**Comment by Founntain** [comment]
Just to clarify it:
>Lets just call it a fucking Song Name Filter, that checks, when turned on, if there are Song Names that are dubs.

What is about songs with the same name but different MP3s? Like long or short versions?
Just do it anyways? Because mostly the songs have long, short or tv size in there name.

Just want to hear your thoughs about that too.

**Comment by Installieren** [comment]
So, if the MP3 name is the same, check the song name( or folder ).
Could you not also check by length? Or is the length of a song only displayed while playing it?

**Comment by Founntain** [comment]
We can check the length but if they are like 0.000000000000000000001 second appart it would not be a dup.
Most MP3s are called `audio.mp3` or a custom name.
And folder should always be different because then we could just check for the beatmapset ID
The song list is already disticted by `folder/audioname`

**Comment by Installieren** [comment]
I mean, then go for Folder name + maybe a small button to just add the song to named Filter.
There is currently nothing else that would make sense at least in my mind.

**Comment by Founntain** [comment]
I'll think about something

**Comment by Founntain** [comment]
@Installieren, Is **[this](https://x.founntain.de/TdBW87h4.mp4)** how you had it in mind?

**Comment by Installieren** [comment]
Hell yes.

**Comment by Founntain** [comment]
Great to hear, sheduled for **v73**
